### ISSUE TITLE
prettify Unitful.jl

### ISSUE THREAD

**Issue by yakir12** [RedPointyJackson/PrettyNumber.jl#1]
Maybe you can help with issue [#92](https://github.com/ajkeller34/Unitful.jl/issues/92#issuecomment-313192739) in `Unitful.jl`? Seems like just the thing for you..?

**Comment by RedPointyJackson** [comment]
Well, I would just change the quantity show function to
````julia
function show(io::IO, x::Quantity)
    prettyval = prettify("$(x.val)") # This was show(io,val)
    print(io, prettyval)
    if !isunitless(unit(x))
        print(io," ")
        show(io, unit(x))
    end
    nothing
end
````
Add `PrettyNumber` to the `REQUIRE` and to the imports of the module, and you get
````
julia> [1, 10, 1e3, 1e6, 1e12, 1.11e15]*mm
6-element Array{Quantity{Float64, Dimensions:{𝐋}, Units:{mm}},1}:
         1 mm
        10 mm
      1000 mm
     1⋅10⁶ mm
    1⋅10¹² mm
 1.11⋅10¹⁵ mm
````
With a warning in Julia 0.6 that I should fix, about a deprecation.

I agree with ajkeller34 about the decoupling of display/storing as misleading. Also,
I would like to note that `PrettyNumber` "rounds" to get a nice representation, eliminating some
of the decimal figures.
